name: CI
on:
  workflow_dispatch:
    branches: [ master ]
    inputs:
      agreement:
        description: "Run manually?"
        type: choice
        options:
          - "yes"
          - "no"
        default: "no"
        required: true

  release:
    types: [published]

jobs:
  check:
    name: Check on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Lint
        run: yarn lint

